feat(aws-s3-sqs): New aws-s3-sqs pattern implementation (#27)
awslabs/aws-solutions-constructs pull request #105
Opened 2020-11-25 01:46 UTC by danielmatuki

closes #27 

Issue #, if available: #27 

Description of changes:
Implements the AWS Solutions Construct that creates an Amazon S3 Bucket connected to an Amazon SQS queue.
In addition, it includes the changes in the s3-bucket-defaults.ts to define the defaultS3NotificationEventTypes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-25 01:52 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-rp7jMDIK1wBN
* Commit ID: 1089629f4c67f64efcba4916d9ebdd9ef89f7200
* Result: FAILED
* [Build Logs](https://nggetq65qd.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e284378f-82da-49f0-937d-78db6a65ed47%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-25 20:12 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-rp7jMDIK1wBN
* Commit ID: bc37eed0eb13c6a981da65c8424a52cb7b86a24b
* Result: SUCCEEDED
* [Build Logs](https://nggetq65qd.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1d23f1cc-c8ee-4fcd-a691-511338efc691%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-27 22:15 UTC, hnishar requested changes
Thanks for the PR, main feedback is around the how the KMS Key related construct props defined and different from other similar patterns (e.g. aws-sns-sqs, aws-events-rule-sns, etc.) in the library.

2020-11-27 22:15 UTC, hnishar commented on source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/integ.deployQueue.ts
> +/**
What is the purpose of this Integration test ? Don't think the name `integ.deployQueue.ts` captures it.

2020-11-27 22:15 UTC, hnishar commented on source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/test.s3-sqs.test.ts
> +  expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
Instead of snapshot, please add the targeted unit test to assert the expected resource(s) exist

2020-11-27 22:15 UTC, hnishar commented on source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/test.s3-sqs.test.ts
> +    expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
Instead of snapshot, please add the targeted unit test to assert the expected resource(s) exist

2020-11-27 22:15 UTC, hnishar commented on source/patterns/@aws-solutions-constructs/aws-s3-sqs/test/test.s3-sqs.test.ts
> +});
Please add a unit test to assert the S3 is granted required permissions to use the KMS Key

2020-12-03 18:58 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-rp7jMDIK1wBN
* Commit ID: 84ae1b9e3e42afbe06f1aa84be10ba5416ac4e3a
* Result: FAILED
* [Build Logs](https://nggetq65qd.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ce5249ff-4b95-46ab-9216-92d4cea7611f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-03 19:21 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-rp7jMDIK1wBN
* Commit ID: f59436f5f93803990b3367b6562de1a84082ac63
* Result: FAILED
* [Build Logs](https://nggetq65qd.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0fcfec91-3d74-4912-a9fd-c4c86fb68fbf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-03 20:53 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-rp7jMDIK1wBN
* Commit ID: d0278824797d5d93f253f12335a7dc1f04ef01c8
* Result: SUCCEEDED
* [Build Logs](https://nggetq65qd.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2be38da6-b9ff-445f-aa73-77ccc7a7cad3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-03 22:11 UTC, danielmatuki commented
@hnishar could you please review the changes?

2020-12-04 00:31 UTC, danielmatuki commented on source/patterns/@aws-solutions-constructs/aws-s3-sqs/lib/index.ts
> +        s3EventTypes.forEach(type => bucket.addEventNotification(type, new s3n.SqsDestination(this.sqsQueue), ...s3Eventfilters));
Yes it will take care of the KMS key resource policy.

2020-12-07 14:58 UTC, purplebari commented on source/patterns/@aws-solutions-constructs/aws-s3-sqs/lib/index.ts
> +    public readonly s3LoggingBucket?: s3.Bucket;
Clarifying - the encryptionKey property should be set to the key for the queue regardless of whether it was passed in or generated by the construct.

2020-12-10 21:45 UTC, blake-enyart commented
@hnishar is there anything I might be able to do to help move this along?

2020-12-16 02:16 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-rp7jMDIK1wBN
* Commit ID: 5d9bd375cb654f035384a19f570e853dac441f46
* Result: SUCCEEDED
* [Build Logs](https://nggetq65qd.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c47542fd-203d-490f-a168-8359bfd516a8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-16 16:33 UTC, merged

2020-12-16 16:34 UTC, hnishar commented
Thanks for the contribution, the updates will go out in v1.77.0 release