Created s3-stepfunctions and eventbridge-stepfunctions construct
awslabs/aws-solutions-constructs pull request #299
Opened 2021-08-02 22:46 UTC by mickychetta

*Issue #286 #287, if available:*

*Description of changes:*
- Created s3-stepfunctions and eventbridge-stepfunctions constructs
- Updated s3-step-function and events-rule-step-function constructs to wrap new constructs 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-02 22:54 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 32456f20621d590e77ef7697aea7d464364df4e0
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bafe3e95-b264-4dd8-aa9c-87dee41df338%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-03 19:55 UTC, biffgaut requested changes
Couple of documentation edits.

2021-08-03 19:55 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/README.md
> +*Note - This construct uses Amazon EventBridge (Amazon CloudWatch Events) to trigger AWS Step Functions. EventBridge is more flexible, but triggering Step Functions with S3 Event Notifications has le
*Note - This construct uses Amazon EventBridge (Amazon CloudWatch Events) to trigger AWS Step Functions State Machine executions. EventBridge is more flexible, but triggering executions with S3 Event Notifications has less latency and is more cost effective. If cost and/or latency is an issue, you should consider deploying aws-s3-lambda and aws-lambda-stepfunctions in place of this construct.*

2021-08-03 21:10 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 987a1cc7d2ccf5f6d18c168f18a1d8e2de5f0289
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a9c5e002-5c19-477b-83a6-73286a4af916%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-03 21:33 UTC, biffgaut requested changes

2021-08-03 21:33 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-eventbridge-stepfunctions/lib/index.ts
> +   * @since 0.9.0
Drop the @since line

2021-08-03 21:33 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-s3-stepfunctions/lib/index.ts
> +   * @since 0.9.0
Drop the @SInCE line

2021-08-03 21:42 UTC, biffgaut approved these changes

2021-08-03 21:46 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: d282066c4294641743a746a27876cf1c4b755e9e
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f9fdf2c1-e2fb-4967-be17-812159f335f0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-03 21:51 UTC, merged