feat(aws-lambda-sqs-lambda) allow passing sqsEventSourceProps into LambdaToSqsToLambda
awslabs/aws-solutions-constructs pull request #321
Opened 2021-08-10 21:38 UTC by mickychetta

*Issue #263 , if available:*

*Description of changes:*
- Added sqsEventSourceProps to LambdaToSqsToLambdaProps and passed it through to the constructor properties of SqsToLambda
- Added sqsEventSourceProps to README

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-10 21:46 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 93b3ba99118502d83166f63f86d08cbaad1f04a2
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9ffa555e-c182-4ffa-9c34-b819b5a0b932%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-10 22:02 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 95f9384bdea52724db2bc59bed3a067797f7d5e9
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3c9252d3-fe88-432c-b044-415f41279a5f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-11 14:15 UTC, biffgaut requested changes

2021-08-11 17:43 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: c09efb86234b9fa8219ce4927202d9c74912e1df
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2f911102-e379-4989-9122-46cad1328b1a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-11 17:48 UTC, biffgaut approved these changes

2021-08-11 17:48 UTC, merged