Added log group props for lambda-dynamodb
awslabs/aws-solutions-constructs pull request #339
Opened 2021-08-17 23:37 UTC by mickychetta

*Issue #316 , if available:*

*Description of changes:*
-Added existingLogGroup prop in buildLogGroup helper function
-Created tests for existing log group and created props
-Updated tests snapshots

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-17 23:45 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 5362949666495fae15be73f5ebf5d19eafb696cf
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7347d68f-c7a6-4f54-b047-83c74ed9d0d5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-17 23:56 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: d1700979ac8d353a3b44a05a495c75fe9b375df3
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=10105ada-0b6e-4c33-806e-f68258b784cf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-18 13:16 UTC, biffgaut requested changes
Stopped the review after reading the docs, because I think there are behavioral changes required that will change a lot of the rest of the code.

2021-08-18 13:16 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/README.md
> +|logGroupProps?|[`logs.LogGroupProps`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-logs.LogGroupProps.html)|Optional user-provided properties to override the default properties for t
This is their chance to override encryptionKey, logGroupName and removalPolicy. The only time we override settings from the client is if the operation of the construct requires certain behavior (eg - endpoints require the DNS settings to be on or they won't work). The issue driving this PR specifically  wanting to set the retention policy, and our tests will probably set the removalPolicy.

2021-08-18 13:16 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-lambda-dynamodb/README.md
> +|existingLogGroup?|[`logs.LogGroup`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-logs.LogGroup.html)|Existing instance of a Log Group object.|
I think we need to clearly state what log group we're discussing - 

An existing Log Group object to assign to the Lambda function.

or below:

Optional user-provided props to configure the Log Group object for the Lambda function.

2021-09-16 18:37 UTC, biffgaut commented
What we're trying to do here can't be accomplished, see linked Issue #316

2021-09-16 18:37 UTC, closed without merging