feat(aws-wafwebacl-apigateway): created README
awslabs/aws-solutions-constructs pull request #355
Opened 2021-09-01 23:14 UTC by mickychetta

*Issue #264 , if available:*

*Description of changes:*
-Created README

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

fixes #264

2021-09-01 23:21 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: dcc46e2b6986d05642cd9bf1e31e4ac54c6692f6
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=89a2ef54-974a-41f6-89d1-0e9e2959fc8f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-02 14:36 UTC, biffgaut requested changes

2021-09-02 14:36 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/README.md
> +const apigatewayInterface = api.RestApi.fromRestApi(this, 'apigateway-interface', apiGateway.restApiId);
You only need to call fromRestApi() when wrapping an IRestApi interface around an existing RestApi. You can just send apiGateway in line 51.

2021-09-02 14:36 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/README.md
> +apiGateway.addMethod('GET', new api.LambdaIntegration(lambdaFunction));
Why don't we just use our own aws-apigateway-lambda construct here rather than lower level CDK commands?

2021-09-02 14:36 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/README.md
> +|existingApiGateway|[`api.IRestApi`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.IRestApi.html)|The existing API Gateway instance that will be fronted with the WAF.|
name this existingApiGatewayInterface

2021-09-02 14:36 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/README.md
> +|existingApiGateway|[`api.IRestApi`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.IRestApi.html)|The existing API Gateway instance that will be fronted with the WAF.|
...that will be protected by the WAF webACL.

2021-09-02 14:36 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/README.md
> +const apigatewayInterface = api.RestApi.fromRestApi(this, 'apigateway-interface', apiGateway.restApiId);
Let's put a comment in this code that this construct can only be attached to a configured API Gateway.

2021-09-02 14:36 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/README.md
> +|existingApiGateway|[`api.IRestApi`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.IRestApi.html)|The existing API Gateway instance that will be fronted with the WAF.|
Add on to this comment:

Note that a WAF web ACL can only be added to a configured API Gateway, so this construct only accepts an existing IRestApi and does not accept apiGatewayProps.

2021-09-02 14:36 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/README.md
> +|apiGateway|[`api.RestApi`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigateway.RestApi.html)|	Returns an instance of the API Gateway REST API created by the pattern. |
Expose IRestApi, not RestApi. When they send us an IRestApi we have no way to convert it to a RestApi.

2021-09-02 14:36 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-wafwebacl-apigateway/README.md
> +    * AWSManagedRulesSQLiRuleSet
Add text here that this list can be replaced by specifying the rules property of CfnWebACLProps.

2021-09-02 17:23 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: 5443b52517dfcf964f5b7727def1ee9aaf62900c
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f726ed5c-a4ce-47d8-b4d6-e2f953f10d8f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-02 17:40 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: codebuildgithubautobuildPro-fkVQbXRiQi6A
* Commit ID: ce09c5929eb45d4c8a59bbb5e9b8409f2ae43928
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=10e67731-6984-4226-b82a-624458058138%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-02 18:33 UTC, biffgaut approved these changes

2021-09-08 21:49 UTC, closed without merging