feat(aws-s3-cloudfront): added condition to omit HTTPS only requests
awslabs/aws-solutions-constructs pull request #559
Opened 2021-12-23 00:52 UTC by mickychetta

*Issue #518 , if available:*

*Description of changes:*
-Added condition to omit HTTPS only requests when enforceSSL is false
-Created tests to check BucketPolicy is correct for enforceSSL prop

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

fixes #518

2021-12-23 00:58 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: b9419115751bad36a6951a1386e20721a4e40438
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=64ad8025-eac6-4887-b14a-e68eea9dd314%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-23 01:01 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: b9419115751bad36a6951a1386e20721a4e40438
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bba52a02-4636-40e8-92e4-ab6455ee9b9a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-23 14:53 UTC, biffgaut requested changes
Just a couple more tests

2021-12-23 14:53 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/core/test/s3-bucket.test.ts
> +test('Test bucket policy that only accepts SSL requests only', () => {
Let's add 2 more tests - 
-SSL is enforced when bucketProps is not provided
-SSL is enforced when bucketProps is provided, but enforceSSL is not set

When we're talking a security issue we want to ensure that every possibility is explicitly tested.

2021-12-23 20:10 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 47ac4b38ae59b9953580cd49eedbd2d32b91bd14
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4fee7bee-228e-4752-a14e-9f09b6203012%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-23 20:12 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 47ac4b38ae59b9953580cd49eedbd2d32b91bd14
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2873c7f6-0753-49cc-9a09-a2a5feecf741%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-23 20:33 UTC, biffgaut requested changes

2021-12-23 20:33 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts
> +  // Apple secure bucket policy through appleSecureBucketPolicy function and not with enforceSSL prop
Pretty sure you meant "Apply"?

2021-12-23 20:33 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/core/lib/s3-bucket-helper.ts
> +  // Set enforceSSL to always false to prevent duplicate policy statement
I don't think we need ApplySecurePolicy anymore - we just need to make sure enforceSSL is always true unless the client explicitly says it should be false.

2021-12-25 07:19 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 5c5e12804379d202e7a47ee3261b6e325665c729
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=91d3369b-958b-478c-858c-0b339e25d07e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-25 07:21 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 5c5e12804379d202e7a47ee3261b6e325665c729
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6e7939cc-b343-4de9-a610-74023c4c57b7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-25 22:36 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 57eb8d182053477fdd1343896496c083f75ba68b
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4deac898-d035-4711-b49b-3e4556804c3f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-25 22:38 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 57eb8d182053477fdd1343896496c083f75ba68b
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b020b133-519f-4535-a65f-81e4604b7fa6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-28 20:28 UTC, biffgaut approved these changes

2021-12-28 20:29 UTC, merged