feat(aws-fargate-sqs): Created new construct
awslabs/aws-solutions-constructs pull request #588
Opened 2022-01-27 20:09 UTC by mickychetta

*Issue #587 , if available:*

*Description of changes:*
-Created new construct with Fargate connected to SQS
-Added environment variables
-Able to create VPC, service, queue, and accept existing ones

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-27 20:16 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: f30b9ec81f51f7800075f8f19d30b192c6c7a760
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=79a6775e-5557-497b-b834-572149137458%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-27 20:17 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: f30b9ec81f51f7800075f8f19d30b192c6c7a760
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2de8ef53-88bc-4fdd-a4ed-4a30ca1f9db4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-27 20:20 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 7bd27ddafbc0053609947a7d781add05657ea741
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a3382c4b-5830-4b73-82c8-b25416e24443%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-27 20:20 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 7bd27ddafbc0053609947a7d781add05657ea741
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=eb009b82-5414-4485-9ed2-35222c0ee91c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-27 20:43 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 645475b67e1cc225ea359c30da7f91338bab1dba
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5cc681d8-a8ed-4da2-af34-4ec678ae55c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-27 20:44 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 645475b67e1cc225ea359c30da7f91338bab1dba
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f60a0943-263d-42eb-93bf-2869bb1abab5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-07 21:52 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: d64658a4f2250b40a4487bd04c5d7d3196dc6223
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=acc67ac5-8f37-4fa8-b067-70e3f3b1a454%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-07 21:53 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: d64658a4f2250b40a4487bd04c5d7d3196dc6223
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4513f543-4e54-45e9-98a9-ef71c7dab6d1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-07 21:58 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 6f1c67ff7df5ebeafc635d1c978e0d85fc7d2779
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7977a117-f197-4843-987b-49e39d3971f0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-07 21:59 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 6f1c67ff7df5ebeafc635d1c978e0d85fc7d2779
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7e7020ab-515b-410c-aea0-2d17a5ca5292%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-07 22:18 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: f9d5e67814104deb91a400e8720dcf0af9a68e32
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8dacf074-4264-4d9a-879a-bfdd4dc40e99%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-07 22:19 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: f9d5e67814104deb91a400e8720dcf0af9a68e32
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=54e19f6b-ef8e-44d9-a512-c3f427fb36c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-15 02:17 UTC, mickychetta commented on source/patterns/@aws-solutions-constructs/aws-fargate-sqs/test/fargate-sqs.test.ts
> +  const publicApi = true;
Yes publicApi is a required construct prop which determine the type of subnets to create. 

publicApi = `true`
'''
// Confirm we created a Public/Private VPC
  expect(stack).toHaveResourceLike('AWS::EC2::InternetGateway', {});
  expect(stack).toCountResources('AWS::EC2::VPC', 1);
  expect(stack).toCountResources('AWS::SQS::Queue', 2);
  expect(stack).toCountResources('AWS::ECS::Service', 1);
'''

publicApi = `false`
'''
// Confirm we created an Isolated VPC
  expect(stack).not.toHaveResourceLike('AWS::EC2::InternetGateway', {});
  expect(stack).toCountResources('AWS::EC2::VPC', 1);
  expect(stack).toCountResources('AWS::SQS::Queue', 1);
  expect(stack).toCountResources('AWS::ECS::Service', 1);
'''

2022-02-15 02:32 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: f191ad2655478fa9ef905d5d10c4caf17136c04f
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b9b4d5d7-bd42-4382-8db8-77d72060c190%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-15 02:36 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: f191ad2655478fa9ef905d5d10c4caf17136c04f
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b17db8b5-661c-4384-9763-5935ff75e6ad%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 15:01 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: f191ad2655478fa9ef905d5d10c4caf17136c04f
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2ce7b14c-e6a6-404f-ba7d-92108a76dbca%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 16:13 UTC, biffgaut requested changes
Some questions, one additional test requested (or update an existing test to check the variation), maybe some trivial changes.

2022-02-16 16:13 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-sqs/test/fargate-sqs.test.ts
> +    fargateTaskDefinitionProps: { family: 'family-name' },
oops - 'family-name' ought to be a constant like those defined in lines 27-31. This is an error in my code in aws-fargate-sqs.

2022-02-16 16:13 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-sqs/test/fargate-sqs.test.ts
> +  const stack = new cdk.Stack(undefined, undefined, {
Same comment

2022-02-16 16:13 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-sqs/test/fargate-sqs.test.ts
> +  expect(stack).toCountResources('AWS::SQS::Queue', 2);
We should have one test that specifies DeadLetterQueue props and checks that a queue with the proper name exists. Looking at all our other SQS constructs, it looks like this is something we have missed completely up to this point.

2022-02-16 18:43 UTC, mickychetta commented on source/patterns/@aws-solutions-constructs/aws-fargate-sqs/lib/index.ts
> +    this.sqsQueue.grantConsumeMessages(this.service.taskDefinition.taskRole);
Did not copy grantConsumeMessages from an existing construct but thinking of different use cases, we should allow users to read and write to the queue

2022-02-16 19:41 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 74e74c60526e17763edff9d9f5039d85920baff3
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=add526aa-9f2b-4664-b076-6d632848cf5b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 19:42 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 74e74c60526e17763edff9d9f5039d85920baff3
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cb2f8e00-ba5f-4c25-8812-1374001c518c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-17 16:54 UTC, biffgaut requested changes
Let's add a prop:

```
|queuePermissions?|`string[]`|Optional queue permissions to grant to the Fargate service. One or more of the following may be specified: `Read`,`Write`. Default is 'Write' |
```

Chose Write for default as a service will be one or the other in most cases so I had to choose one. Since the preferred way to read a queue is a event driven Lambda function, I chose write - but I'm open to discussion.

2022-02-17 20:56 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 65a451252ad4b38b4f137be2be6025ce01f8a69a
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3b5a7569-bb1d-4ff3-8f19-dd84f9930f5e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-19 15:24 UTC, biffgaut approved these changes

2022-02-19 15:38 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: b753cd96143923b8c149fa3b9f791c3a689a4cb6
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e2910298-3b34-4bdf-b4a7-0d98a54119e4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-19 15:40 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: b753cd96143923b8c149fa3b9f791c3a689a4cb6
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f48b2e62-a57a-4a0e-8df6-641ac8a12c7c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-22 18:51 UTC, merged