feat(aws-fargate-s3): Created new construct
awslabs/aws-solutions-constructs pull request #591
Opened 2022-02-08 00:27 UTC by mickychetta

*Issue #590 , if available:*

*Description of changes:*
-Created new construct of aws-fargate-s3
-Added environment variables in fargate environment to allow read/write to bucket
-Created unit/integ tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

fixes #590

2022-02-08 00:34 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 6265f151ea455ef1d9864719654809ce7696d0b9
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=82f20f44-e73a-49cb-9a63-af0eb7db77ec%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-08 00:35 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 6265f151ea455ef1d9864719654809ce7696d0b9
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6f122101-c9ee-450d-b111-71a51b1d8978%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-10 00:47 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: aec48ca35173bb27dc5ef837ff05fbc9b326db92
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=31c7dd89-0785-4c55-ab88-612e237ab9f6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-10 00:47 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: aec48ca35173bb27dc5ef837ff05fbc9b326db92
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8c2a8ea3-28fa-4acb-81c1-5017f4020087%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-10 00:57 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 845bd7c5e2b6d46781c12b51bd2aa58126b4eca8
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=398b3b51-a266-45cf-a6d1-cadb34f1efe8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-10 01:02 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 845bd7c5e2b6d46781c12b51bd2aa58126b4eca8
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1e7754c6-e89d-437f-9f9e-ef6f97138bb5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-10 01:04 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: dd8c5ea747ba62a4d9158740b6b1b808878c6a21
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=38d9f0a7-80d8-41bc-bf4a-23b20ca43dc4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-10 01:09 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: dd8c5ea747ba62a4d9158740b6b1b808878c6a21
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=10350979-0a74-43d0-89c5-a18676ad75af%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 21:58 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 19a7f594aa9cb0b233829c1e036f41c74f70b192
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8f232368-b4d7-456e-a3d3-c70d8ec97cc1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 21:59 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 19a7f594aa9cb0b233829c1e036f41c74f70b192
* Result: FAILED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d4dbee90-a15a-468a-a99b-d345671d6b5b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 22:31 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 07e432281816c3a9a6b361e263ab9911a22d8003
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8c670600-9b60-4426-80d9-af1b5af08961%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 22:32 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 07e432281816c3a9a6b361e263ab9911a22d8003
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=21fc5571-c3f6-4be4-93cf-c68839dce938%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-17 18:18 UTC, biffgaut requested changes
Similar issue around permissions. Change should very simple.

Testing for conditions needs improvement.

2022-02-17 18:18 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-s3/test/fargate-s3.test.ts
> +    bucketPermissions: ['Delete', 'Put', 'Read', 'ReadWrite', 'Write']
There's no check on these in any of the tests.  Including all the options will run al the code and get you 100% coverage, but without confirmation of the output it's just a gimmick to increase the coverage total.

One test should specify a subset, then confirm the result (probably have to confirm with a non-granular check like line 75.

2022-02-17 22:45 UTC, mickychetta commented on source/patterns/@aws-solutions-constructs/aws-fargate-s3/README.md
> +|bucketPermissions?|`string[]`|Optional bucket permissions to grant to the Lambda function. One or more of the following may be specified: `Delete`, `Put`, `Read`, `ReadWrite`, `Write`.|
The default bucket permissions in aws-lambda-s3 is `ReadWrite` which composes of Read, Write, and Delete operations so I will stick to to that for consistency. I allowed Read, Write, and Delete strings for bucketPermissions  in order to create a more fine-grained policy. I removed Put as it is repetitive and made ReadWrite as default which separates confusion from inputs.

2022-02-17 22:54 UTC, mickychetta commented on source/patterns/@aws-solutions-constructs/aws-fargate-s3/README.md
> +|bucketPermissions?|`string[]`|Optional bucket permissions to grant to the Lambda function. One or more of the following may be specified: `Delete`, `Put`, `Read`, `ReadWrite`, `Write`.|
We will need to make following changes to aws-lambda-s3 if we agree with this.

2022-02-17 23:34 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 27b900622b57f4e697368c9b5e52b9543b8ac152
* Result: FAILED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=07cb4ae0-7277-4d84-b574-ac27f41eca03%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-17 23:37 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 27b900622b57f4e697368c9b5e52b9543b8ac152
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2725a532-9fb9-4ce2-b907-7c0751af04a1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-19 00:00 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: f14cc541810f30484a916488fcbc4d9767b2c921
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8977a01c-dfc2-458c-a642-f7d4b12d1b72%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-19 15:19 UTC, biffgaut requested changes
Couple of changes to ensure backwards compatibility with existing stacks.

2022-02-19 15:19 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-s3/README.md
> +|bucketPermissions?|`string[]`|Optional bucket permissions to grant to the Fargate service. One or more of the following may be specified: `Delete`, `Read`, and `Write`. Default is `ReadWrite` which
Need to change this to Default is 'Read' and 'Write' as we don't want to give the impression that ReadWrite is not deprecated. I like that we don't list it here - I assume the code still allows it for backwards compatibility.

If the code looks good I can approve this now and we can make a quick inline change of this comment later.

2022-02-19 15:19 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-s3/lib/index.ts
> -      if (props.bucketPermissions.includes('ReadWrite')) {
We can't delete this functionality as that will break existing clients - we should drop them from the doc but leave the code that supports them in place along with comments that 'Put' and 'ReadWrite' are deprecated but this code remains for backwards compatibility.

```
   // ReadWrite and Put are deprecated, but included here for backwards compatibility
   if (props.bucketPermissions.includes('Write') || 
        props.bucketPermissions.includes{'ReadWrite') ||
        props.bucketPermissions.includes('Put') )
   {
        ...
   }
   if (props.bucketPermissions.includes('Read') || props.bucketPermissions.include('ReadWrite') {
      ...
   }

etc.

  if (props.bucketPermissions.includes('ReadWrite') || props.bucketPermissions.includes('Put')) {
    printWarning('Put and ReadWrite are deprecated, please switch to some combination of Read, Write and Delete');
  }

```

2022-02-19 15:27 UTC, biffgaut approved these changes
Ignore my comments about backwards compatibility - I was thinking aws-lambda-s3 and this is a brand new construct.

2022-02-19 15:27 UTC, merged