fix(cdk-integ-tools): Ignore the diff for S3AutoDeleteObjects lambda function from cdk-integ-assert
awslabs/aws-solutions-constructs pull request #628
Opened 2022-03-17 20:59 UTC by hnishar

*Issue #, if available: [627](https://github.com/awslabs/aws-solutions-constructs/issues/627)*

*Description of changes: Ignore the diff for S3AutoDeleteObjects lambda function from cdk-integ-assert* 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-03-17 21:07 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: ce77d560f5f268f82a4a7c33288aa7cf5ef3c13f
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=44161c5f-b07c-49b1-950c-8745dd7bc808%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-17 21:07 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: ce77d560f5f268f82a4a7c33288aa7cf5ef3c13f
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5260bcaa-935e-4431-ac70-dbf443cbbb34%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 12:34 UTC, biffgaut requested changes
Let's add some documentation so we can reproduce all customizations when we next refresh cdk-integ to ensure that you are a memory we speak of fondly :-)

Let's add a file called "solutions-constructs-modifications.md" containing:

## Customizations that need to be reapplied whenever cdk-integ is updated

**Check for Lambda Functions to Ignore**
canonicalize-assets.ts
* add line `import { LIST_OF_IGNORE_LAMBDA_PREFIX } from "./integ-helpers";`
* add `HideIgnoredFunctions()`
* add `CheckIgnoreList()`

integ-helpers.ts
* Add section with `LIST_OF_IGNORED_LAMBDA_PREFIXES

(plus any other customizations we have made in the past)

2022-03-18 12:34 UTC, biffgaut commented on source/tools/cdk-integ-tools/lib/canonicalize-assets.ts
> +  function checkIgnoreList(functionName: string): boolean {
Don't hide a function inside another function (that's the case here, right? Hard to tell in github).

2022-03-18 12:34 UTC, biffgaut commented on source/tools/cdk-integ-tools/lib/canonicalize-assets.ts
> +  for (const [resourceName, resourceValue] of Object.entries(template?.Resources || {})) {
This code could be self documenting if we moved this block out to a function:

```
function HideIgnoredResources(entries) {
    if (checkIgnoreList(resourceName)) {
      stringSubstitutions.push([
        (resourceValue as any).Properties.Code.S3Key,
        'SomeHash.zip'
      ])
    }
}
```

* needs better types on the declaration
* Probably some syntax issues in my version. :-)

2022-03-18 12:34 UTC, biffgaut commented on source/tools/cdk-integ-tools/lib/integ-helpers.ts
> +export const LIST_OF_IGNORE_LAMBDA_PREFIX = [
make plural (it's a list): LIST_OF_IGNORED_LAMBDA_PREFIXES

2022-03-18 20:03 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 497a6d55063793f0fd154f467bc80b0ba3c1a79a
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=946961be-cab9-4e6d-9501-f140fd0c73e5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 20:19 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 2fe99149f49fb8a41a38ffbb69fdd067c4e42eab
* Result: SUCCEEDED
* [Build Logs](https://j8dgcooz5f.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5ab406e0-741d-4d55-904e-164da542fdf8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 20:21 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v1
* Commit ID: 2fe99149f49fb8a41a38ffbb69fdd067c4e42eab
* Result: SUCCEEDED
* [Build Logs](https://nis3u8ftb6.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8cc7fefb-a7ed-4b60-ab4a-148869e79cb3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-19 15:09 UTC, biffgaut approved these changes

2022-03-19 15:09 UTC, merged