feat(new construct): aws-fargate-kinesisfirehose
awslabs/aws-solutions-constructs pull request #881
Opened 2022-12-22 19:54 UTC by biffgaut

Closes Issue #880 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-22 20:01 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: e9d23112b5ae6c593d7365929708c2b5f3c05c19
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ac872147-4186-4c97-ab26-b3db4ff1280b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-22 20:01 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 74bce069928a7552f4363f904eea91a14fff61db
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=170ed53e-a9d7-4e0d-87ea-c63aa4ba12a3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-22 20:05 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 9e902eea829aaf9d2b827cb7f227bf751a09c664
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=49bf7534-d1d3-43d3-aaac-019bb231914f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-22 20:17 UTC, georgebearden approved these changes
looks good to me

2022-12-22 20:17 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/README.md
> +const existingFirehoseDeliveryStream = previoslyCreatedKinesisFirehoseToS3Construct.kinesisFirehose;
Nit typo - previosly -> previously

2022-12-22 20:17 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/README.md
> +const existingFirehoseDeliveryStream = previoslyCreatedKinesisFirehoseToS3Construct.kinesisFirehose;
Same nit in the other code samples

2022-12-26 15:32 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: e8b71db736330d1e501e9987f213422e020155ba
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3657cd46-7afa-4922-8ab9-419723119ad0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-26 16:15 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: c2f6b04baf0104e42ad226b35275d740b65cdf8e
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=628472f5-11f2-4aae-a2c4-c6f0813198c4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-26 17:45 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: f75e926039f9fd7a70903c6f59d9a9fd80774c26
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2cfaac7c-4d14-492a-84bf-d867c699e421%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-26 17:59 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 75f63418670c41840bc3006da4ca951d9c6cfc42
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c68e0e3d-68c6-4c85-be4c-f3dc35ef1399%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-27 15:12 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/test/aws-fargate-kinesisfirehose.test.ts
> +  // const clusterName = "custom-cluster-name";
Delete commented out code

2022-12-27 15:12 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/test/aws-fargate-kinesisfirehose.test.ts
> +  // An environment with region is required to enable logging on an ALB
Delete comment

2022-12-27 15:12 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/test/aws-fargate-kinesisfirehose.test.ts
> +// TODO: change test-fargate-kinesistreams id to firehose
delete (confirm this was done)

2022-12-27 15:12 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/test/integ.noArguments.ts
> +// Synth
Get rid of these comments

2022-12-27 15:12 UTC, biffgaut commented on source/patterns/@aws-solutions-constructs/aws-lambda-kinesisfirehose/README.md
> +  existingKinesisFirehose: existingFirehoseDeliveryStream
indention issue here

2022-12-27 15:49 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: c27ff37ea271919dec1ed317d9db3e2f47685a17
* Result: FAILED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4cf71eb7-3c64-4cb3-9464-5a7ab3e7ae89%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-27 17:07 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 982b68cb7e97feff681bdc1af994aa1327bacdc9
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b6a73708-18df-48d4-bd21-e046d4c509e8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-28 15:27 UTC, georgebearden requested changes
There are two architecture diagrams, one in a root level `BIN` folder and another in this constructs folder. Let's make sure to clean up that discrepancy.

2022-12-28 15:27 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/README.md
> +const existingFirehoseDeliveryStream = previouslyCreatedKinesisFirehoseToS3Construct.kinesisFirehose;
remove the `const` here

2022-12-28 15:27 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/README.md
> +const existingFirehoseDeliveryStream = previouslyCreatedKinesisFirehoseToS3Construct.kinesisFirehose;
remove the `const` here

2022-12-28 15:27 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/lib/index.ts
> +   * An existing Kinesis Firehose Delivery Stream to which the Lambda function can put data. Note - the delivery stream
Nit - change `Lambda function` to `Fargate Service`

2022-12-28 15:27 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/lib/index.ts
> +   * @default - none
Nit based on the last fargate-kinesisstreams PR - remove the `@default - none` since this ins't an optional property.

2022-12-28 15:27 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-fargate-kinesisfirehose/package.json
> +  "version": "2.29.0",
In this file, there are many explicit version numbers here and din the dependency sections below. Most of these should be set to 0.0.0, like [here](https://github.com/awslabs/aws-solutions-constructs/blob/main/source/patterns/%40aws-solutions-constructs/aws-fargate-kinesisstreams/package.json), correct?

2022-12-28 15:27 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-lambda-kinesisfirehose/README.md
> +const existingFirehoseDeliveryStream = previouslyCreatedKinesisFirehoseToS3Construct.kinesisFirehose;
Remove `const`

2022-12-28 15:27 UTC, georgebearden commented on source/patterns/@aws-solutions-constructs/aws-lambda-kinesisfirehose/README.md
> +const existingFirehoseDeliveryStream = previouslyCreatedKinesisFirehoseToS3Construct.kinesisFirehose;
remove `const`

2022-12-28 16:07 UTC, aws-solutions-constructs-team commented
### AWS CodeBuild CI Report

* CodeBuild project: githubautobuild-for-cdk-v2
* Commit ID: 71da342a9149d065cf7823a2eab04c5b879d995a
* Result: SUCCEEDED
* [Build Logs](https://t2ulkoluaf.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=270a361a-8465-4b96-9fa0-756c26968e81%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-28 16:13 UTC, georgebearden approved these changes
looks good to me

2022-12-28 16:13 UTC, merged